export const PART_2 = [
    // --- GEOGRAFI (50) ---
    { category: "Geografi", questionText: "Hva er hovedstaden i Tyskland?", options: ["München", "Hamburg", "Berlin", "Frankfurt"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket land er verdens største i areal?", options: ["USA", "Kina", "Canada", "Russland"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "Hva er verdens lengste elv?", options: ["Amazonas", "Nilen", "Mississippi", "Yangtze"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "I hvilken verdensdel ligger Sahara-ørkenen?", options: ["Asia", "Sør-Amerika", "Afrika", "Australia"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hva heter det høyeste fjellet i Norge?", options: ["Glittertind", "Snøhetta", "Galdhøpiggen", "Gaustatoppen"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket hav ligger mellom Europa og Amerika?", options: ["Stillehavet", "Atlanterhavet", "Indiske hav", "Ishavet"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva er hovedstaden i Japan?", options: ["Beijing", "Seoul", "Tokyo", "Bangkok"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket land har flest innbyggere?", options: ["India", "Kina", "USA", "Indonesia"], correctAnswerIndex: 0 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Italia?", options: ["Milano", "Venezia", "Roma", "Napoli"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket fylke ligger Porsgrunn i (historisk)?", options: ["Vestfold", "Telemark", "Agder", "Viken"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter verdens største øy?", options: ["Grønland", "Australia", "Madagaskar", "Borneo"], correctAnswerIndex: 0 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Sverige?", options: ["Stocholm", "København", "Helsinki", "Oslo"], correctAnswerIndex: 0 },
    { category: "Geografi", questionText: "Hvilket land er kjent for 'tulipaner'?", options: ["Danmark", "Belgia", "Nederland", "Tyskland"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "I hvilken by finner du Colosseum?", options: ["Athen", "Roma", "Paris", "London"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilket land grenser Norge tik i øst?", options: ["Danmark", "Sverige", "Island", "Tyskland"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter den største staten i USA (areal)?", options: ["Texas", "California", "Alaska", "Florida"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilken verdensdel bor det flest mennesker i?", options: ["Afrika", "Europa", "Nord-Amerika", "Asia"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "Hva heter fjellet som er kjent som 'Verdens tak'?", options: ["K2", "Mount Everest", "Fuji", "Kilimanjaro"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Frankrike?", options: ["Lyon", "Marseille", "Paris", "Nice"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "I hvilket land ligger byen Barcelona?", options: ["Portugal", "Spania", "Italia", "Frankrike"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilken elv renner gjennom London?", options: ["Seinen", "Donau", "Rhinen", "Themsen"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "Hva heter det minste landet i verden?", options: ["Monaco", "Lichtenstein", "Vatikanstaten", "San Marino"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket land er kjent som 'The Land of the Rising Sun'?", options: ["Kina", "Sør-Korea", "Vietnam", "Japan"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Danmark?", options: ["Aarhus", "Odense", "København", "Aalborg"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket hav grenser Norge til i vest?", options: ["Østersjøen", "Nordsjøen/Norskehavet", "Middelhavet", "Svartehavet"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "I hvilket land ligger pyramidene i Giza?", options: ["Mexico", "Egypt", "Peru", "Sudan"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter den største innsjøen i Norge?", options: ["Røssvatnet", "Femunden", "Mjøsa", "Tyrifjorden"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilken amerikansk stat er en øygruppe?", options: ["Alaska", "Florida", "Hawaii", "California"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Spania?", options: ["Barcelona", "Sevilla", "Madrid", "Valencia"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilken verdensdel ligger Brasil i?", options: ["Nord-Amerika", "Sør-Amerika", "Afrika", "Europa"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter kanalen som deler Nord- og Sør-Amerika?", options: ["Suezkanalen", "Panamakanalen", "Kielkanalen", "Korintkanalen"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilket land er IKKE i Skandinavia?", options: ["Sverige", "Finland", "Danmark", "Norge"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket fjell ligger i Cape Town?", options: ["Table Mountain", "Sugarloaf", "Mount Kenya", "Atlas"], correctAnswerIndex: 0 },
    { category: "Geografi", questionText: "Hva heter myntenheten i USA?", options: ["Euro", "Pund", "Dollar", "Yen"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilken by kalles 'The Big Apple'?", options: ["Los Angeles", "Chicago", "Miami", "New York"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "I hvilket land ligger Taj Mahal?", options: ["Thailand", "India", "Kina", "Nepal"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter det store revet utenfor Australia?", options: ["Great Barrier Reef", "Blue Hole", "Coral Bay", "Shark Reef"], correctAnswerIndex: 0 },
    { category: "Geografi", questionText: "Hvilket land er formet som en støvel?", options: ["Spania", "Hellas", "Italia", "Portugal"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilken by er hovedstaden i Russland?", options: ["St. Petersburg", "Moskva", "Kazan", "Sochi"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilket kontinent er det eneste uten faste beboere?", options: ["Australia", "Antarktis", "Sør-Amerika", "Afrika"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter den lengste elven i Europa?", options: ["Donau", "Rhinen", "Volga", "Elben"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket land grenser både til Tyskland og Belgia?", options: ["Polen", "Nederland", "Danmark", "Østerrike"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilken by er kjent for sine gondoler?", options: ["Roma", "Firenze", "Milano", "Venezia"], correctAnswerIndex: 3 },
    { category: "Geografi", questionText: "Hva het landet Myanmar før?", options: ["Siam", "Burma", "Ceylon", "Rhodesia"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilken stat i USA har forkortelsen 'TX'?", options: ["Tennessee", "Texas", "Tucson", "Tampa"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hva heter hovedstaden i Kina?", options: ["Shanghai", "Beijing", "Hong Kong", "Wuhan"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvilket språk snakker flest i Canada (ved siden av engelsk)?", options: ["Spansk", "Tysk", "Fransk", "Italiensk"], correctAnswerIndex: 2 },
    { category: "Geografi", questionText: "Hvilket hav omkranser Island?", options: ["Stillehavet", "Atlanterhavet", "Indiske hav", "Middelhavet"], correctAnswerIndex: 1 },
    { category: "Geografi", questionText: "Hvor ligger Machu Picchu?", options: ["Chile", "Argentina", "Peru", "Bolivia"], correctAnswerIndex: 2 },


    // --- VITENSKAP (50) ---
    { category: "Vitenskap", questionText: "Hva er det kjemiske symbolet for vann?", options: ["HO", "H2O", "O2", "CO2"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvilken planet er nærmest solen?", options: ["Venus", "Mars", "Merkur", "Jorden"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva måler man med et termometer?", options: ["Trykk", "Temperatur", "Fuktighet", "Vindstyrke"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvilket organ pumper blod rundt i kroppen?", options: ["Lunger", "Hjerne", "Hjerte", "Lever"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er lysets hastighet (ca)?", options: ["300 000 km/s", "100 000 km/s", "500 000 km/s", "1 000 km/s"], correctAnswerIndex: 0 },
    { category: "Vitenskap", questionText: "Hvilken gass trenger mennesker for å puste?", options: ["Helium", "Oksygen", "Karbon", "Nitrogen"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter vår galakse?", options: ["Andromeda", "Melkeveien", "Triangulum", "Sombrero"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvilket dyr er verdens største pattedyr?", options: ["Elefant", "Blåhval", "Sjiraff", "Neshorn"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva studerer man i botanikk?", options: ["Dyr", "Steiner", "Planter", "Stjerner"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er kokepunktet til vann ved havnivå?", options: ["90 grader", "100 grader", "110 grader", "120 grader"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvem utviklet relativitetsteorien?", options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Stephen Hawking"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilket grunnstoff har symbolet 'O'?", options: ["Osmium", "Oksygen", "Opium", "Oktan"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva kalles læren om stjernene?", options: ["Geologi", "Biologi", "Astronomi", "Astrologi"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvor mange bein har en edderkopp?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva er den hardeste naturlige steinen?", options: ["Granitt", "Marmor", "Diamant", "Kalkstein"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilken planet kalles 'Den røde planeten'?", options: ["Jupiter", "Mars", "Saturn", "Venus"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva står 'DNA' for (forenklet)?", options: ["Arvestoff", "Blodtype", "Cellevegg", "Vitaminer"], correctAnswerIndex: 0 },
    { category: "Vitenskap", questionText: "Hvilket dyr sier 'mø'?", options: ["Sau", "Gris", "Ku", "Hest"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva bruker planter til fotosyntese?", options: ["Måneskinn", "Sollys", "Ild", "Vind"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter den største planeten i solsystemet?", options: ["Saturn", "Jupiter", "Uranus", "Neptun"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvor mange tenner har et voksent menneske (vanligvis)?", options: ["28", "30", "32", "34"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilket instrument brukes til å se på små ting?", options: ["Teleskop", "Mikroskop", "Periskop", "Stetoskop"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva fryser vann til ved 0 grader?", options: ["Damp", "Gass", "Is", "Plasma"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilket grunnstoff er Au?", options: ["Sølv", "Gull", "Aluminium", "Argon"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter vitenskapsmannen som fikk et eple i hodet?", options: ["Einstein", "Newton", "Gallilei", "Darwin"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva er det minste byggeklossen i kroppen?", options: ["Organ", "Vev", "Celle", "Knokkel"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilket dyr kan skifte farge?", options: ["Løve", "Kameleon", "Zebra", "Bjørn"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva kalles det når månen dekker for solen?", options: ["Måneformørkelse", "Solformørkelse", "Fullmåne", "Nymåne"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva består skyer hovedsakelig av?", options: ["Bomull", "Røyk", "Vanndamp", "Støv"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilken dinosaur hadde korte armer og store tenner?", options: ["Triceratops", "Stegosaurus", "T-Rex", "Diplodocus"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er pH-verdien til rent vann?", options: ["5", "7", "9", "10"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva skjer med varm luft?", options: ["Den synker", "Den stiger", "Den står stille", "Den blir til is"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvilket dyr er en 'amfibie'?", options: ["Laks", "Frosk", "Ørn", "Hund"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva er solsystemets sentrum?", options: ["Jorden", "Månen", "Solen", "Mars"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilken kraft holder oss på bakken?", options: ["Magnetisme", "Elektrisitet", "Tyngdekraft", "Friksjon"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er hovedbestanden i luft?", options: ["Oksygen", "Nitrogen", "Karbondioksid", "Hydrogen"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva kalles en unge av en frosk?", options: ["Larve", "Rumpetroll", "Yngel", "Valp"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvor mange hjerter har en blekksprut?", options: ["1", "2", "3", "4"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er det raskeste landdyret?", options: ["Løve", "Gepard", "Antilope", "Hest"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva bruker en kompassnål for å vise nord?", options: ["Vind", "Magnetisme", "Sollys", "Tyngdekraft"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter beinet i overarmen?", options: ["Lårbein", "Humerus", "Radius", "Ulna"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hvor mange planeter er det i solsystemet?", options: ["7", "8", "9", "10"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter det når vann blir til damp?", options: ["Smelting", "Fordamping", "Kondensering", "Frysing"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva er batterier laget for å lagre?", options: ["Vann", "Luft", "Energi", "Varme"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hvilken fugl kan ikke fly?", options: ["Ørn", "Pingvin", "Due", "Måke"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva er skjelettet laget av?", options: ["Muskler", "Bein", "Hud", "Sener"], correctAnswerIndex: 1 },
    { category: "Vitenskap", questionText: "Hva heter det når jorden snurrer rundt seg selv?", options: ["Rotasjon", "Revolusjon", "Orbit", "Akselerasjon"], correctAnswerIndex: 0 },
    { category: "Vitenskap", questionText: "Hvilken type sky gir ofte regn?", options: ["Cirrus", "Cumulus", "Nimbus", "Stratus"], correctAnswerIndex: 2 },
    { category: "Vitenskap", questionText: "Hva er det hardeste stoffet i menneskekroppen?", options: ["Bein", "Emalje (tenner)", "Negler", "Hud"], correctAnswerIndex: 1 },


    // --- LETT BLANDING (50) ---
    { category: "Lett blanding", questionText: "Hvor mange dager er det i et skuddår?", options: ["364", "365", "366", "367"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilken farge får du om du blander rød og hvit?", options: ["Lilla", "Rosa", "Oransje", "Brun"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter hunden til Mikke Mus?", options: ["Langbein", "Pluto", "Snoopy", "Lassie"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilken valuta brukes i Storbritannia?", options: ["Euro", "Dollar", "Pund", "Krone"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva står forkortelsen 'NRK' for?", options: ["Norsk Rikskringkasting", "Norges Røde Kors", "Norsk Radio Kanal", "Nordisk Radio Kringkasting"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hvor mange ben har en edderkopp?", options: ["6", "8", "10", "12"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilken måned er årets korteste?", options: ["Januar", "Februar", "April", "Desember"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter det norske kongeparet?", options: ["Harald og Sonja", "Olav og Märtha", "Haakon og Mette-Marit", "Carl og Silvia"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hva kalles en babykatt?", options: ["Valp", "Kylling", "Kattunge", "Føll"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilket språk snakker man i Brasil?", options: ["Spansk", "Portugisisk", "Fransk", "Engelsk"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er Norges nasjonaldag?", options: ["1. mai", "17. mai", "7. juni", "4. juli"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvor mange minutter er det i en time?", options: ["50", "60", "90", "100"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er 'Facebook'?", options: ["En bok", "Et sosialt nettverk", "En avis", "Et spill"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter bilen til Batman?", options: ["Batmobile", "Supercar", "Black Wing", "Night Rider"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hva bruker man for å surfe på internett?", options: ["Brødrister", "Nettleser", "Mikrobølgeovn", "Kjøleskap"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilken farge er det på et stoppskilt?", options: ["Blått", "Grønt", "Rødt", "Gult"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva heter det kjente tårnet i Paris?", options: ["Pisa", "Eiffeltårnet", "Big Ben", "Empire State"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er hovedingrediensen i brød?", options: ["Mel", "Sukker", "Egg", "Melk"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hvilket dyr er 'Bambi'?", options: ["Kanin", "Rådyr", "Rev", "Bjørn"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter nissen på engelsk?", options: ["Santa Claus", "Easter Bunny", "Tooth Fairy", "Jack Frost"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hvor mange hjul har en bil vanligvis?", options: ["2", "3", "4", "6"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva kalles en person fra Sverige?", options: ["Dansk", "Svensk", "Norsk", "Finsk"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva betyr 'Ciao' på italiensk?", options: ["Takk", "Hei/Ha det", "God natt", "Vær så god"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilket instrument har pedaler?", options: ["Gitar", "Piano", "Fløyte", "Fiolin"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter den store klokken i London?", options: ["Little John", "Big Ben", "Giant George", "Tall Tom"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er halvparten av 100?", options: ["25", "40", "50", "60"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva heter verdens mest kjente brus?", options: ["Pepsi", "Fanta", "Sprite", "Coca-Cola"], correctAnswerIndex: 3 },
    { category: "Lett blanding", questionText: "Hvilken farge har smurfene?", options: ["Grønne", "Røde", "Blå", "Gule"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva bruker man for å klippe papir?", options: ["Hammer", "Sag", "Saks", "Skrutrekker"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva heter julenissens reinsdyr med rød nese?", options: ["Dasher", "Prancer", "Rudolf", "Vixen"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilken dag kommer etter fredag?", options: ["Onsdag", "Torsdag", "Lørdag", "Søndag"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva er det motsatte av 'varm'?", options: ["Lunken", "Kald", "Het", "Tørr"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter det når man sover om vinteren (dyr)?", options: ["Dvale", "Ferie", "Siesta", "Koma"], correctAnswerIndex: 0 },
    { category: "Lett blanding", questionText: "Hvor har man på seg en 'hatt'?", options: ["Foten", "Hodet", "Hånden", "Magen"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilken måned feirer vi jul?", options: ["November", "Desember", "Januar", "Februar"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter hovedstaden i Norge?", options: ["Bergen", "Trondheim", "Oslo", "Stavanger"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilken farge har gresset (vanligvis)?", options: ["Blått", "Rødt", "Grønt", "Lilla"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva bruker man for å pusse tennene?", options: ["Hårbørste", "Tannbørste", "Oppvaskkost", "Feiekost"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er 5 pluss 5?", options: ["8", "9", "10", "11"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilket dyr sier 'voff'?", options: ["Katt", "Hund", "Fugl", "Fisk"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva kommer ut av en vulkan?", options: ["Vann", "Lava", "Is", "Sand"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter den gule svampen?", options: ["Patrick", "Svampebob", "Sandy", "Mr. Krabs"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hvilken bilmerke har en stjerne i logoen?", options: ["Audi", "BMW", "Mercedes", "Volvo"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hva heter det når det regner og er sol samtidig?", options: ["Snøstorm", "Regnbue", "Tåke", "Hagl"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er vann frosset til is?", options: ["Flytende", "Fast", "Gass", "Plasma"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva er det engelske ordet for 'bil'?", options: ["Bike", "Plane", "Car", "Boat"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilken farge er sitron?", options: ["Oransje", "Gul", "Grønn", "Rød"], correctAnswerIndex: 1 },
    { category: "Lett blanding", questionText: "Hva heter det når man fyller år?", options: ["Begravelse", "Bryllup", "Bursdag", "Konfirmasjon"], correctAnswerIndex: 2 },
    { category: "Lett blanding", questionText: "Hvilket dyr gir oss melk?", options: ["Gris", "Høne", "Ku", "Hest"], correctAnswerIndex: 2 },


    // --- MAT OG DRIKKE (50) ---
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i guacamole?", options: ["Tomat", "Løk", "Avokado", "Agurk"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilket land kommer pizza fra?", options: ["USA", "Frankrike", "Spania", "Italia"], correctAnswerIndex: 3 },
    { category: "Mat og drikke", questionText: "Hva er sushi tradisjonelt laget av?", options: ["Kjøtt", "Rå fisk og ris", "Stekt fisk og poteter", "Grønnsaker"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva kalles den spanske småretten?", options: ["Tapas", "Paella", "Tacos", "Burrito"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken drikk er laget av druer?", options: ["Øl", "Cider", "Vin", "Vodka"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i marsipan?", options: ["Mel", "Mandler", "Kokos", "Ris"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hvilket land produserer mest ost i verden?", options: ["Frankrike", "USA", "Tyskland", "Italia"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'tofu' laget av?", options: ["Melk", "Soya", "Ris", "Hvete"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hvilken type pasta ser ut som små slips?", options: ["Spaghetti", "Penne", "Farfalle", "Fusilli"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva kalles sausen man ofte har på taco (rød)?", options: ["Salsa", "Guacamole", "Rømme", "Pesto"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken nøtt er hovedingrediensen i Nutella?", options: ["Peanøtt", "Valnøtt", "Hasselnøtt", "Cashewnøtt"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er Norges nasjonalrett (uoffisielt)?", options: ["Pizza Grandiosa", "Fårikål", "Kjøttkaker", "Lutefisk"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hvilken frukt er kjent som 'forbuden frukt'?", options: ["Banan", "Eple", "Pære", "Drue"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i hummus?", options: ["Linser", "Bønner", "Kikerter", "Erter"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilket krydder er verdens dyreste?", options: ["Vanilje", "Kardemomme", "Safran", "Kanel"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er 'Gouda'?", options: ["En by", "En ost", "En pølse", "En vin"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva heter det når man steker brød i en maskin?", options: ["Risting", "Koking", "Grilling", "Baking"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken grønnsak skal vampyrer hate?", options: ["Løk", "Hvitløk", "Gulrot", "Potet"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i en omelett?", options: ["Melk", "Mel", "Egg", "Sukker"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilket bær er blått og lager flekker?", options: ["Jordbær", "Blåbær", "Bringebær", "Tyttebær"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i øl?", options: ["Poteter", "Ris", "Malt/Korn", "Druer"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilke land er kjent for baguette?", options: ["Tyskland", "Italia", "Spania", "Frankrike"], correctAnswerIndex: 3 },
    { category: "Mat og drikke", questionText: "Hva er 'Chili Con Carne'?", options: ["Chili med kjøtt", "Chili med fisk", "Chili med kylling", "Chili vegetar"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken sitrusfrukt er grønn?", options: ["Sitron", "Appelsin", "Lime", "Orapefrukt"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er den sterkeste frukten?", options: ["Chili", "Paprika", "Tomat", "Agurk"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hva heter den kjente hamburgerkjeden?", options: ["McDougal's", "McDonald's", "McDavid's", "McDaniel's"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'kebab' opprinnelig?", options: ["Grillet kjøtt", "Kokt fisk", "Stekt grønnsak", "Bakt brød"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken farge har innsiden av en kiwi?", options: ["Gul", "Rød", "Grønn", "Blå"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i sjokolade?", options: ["Sukker", "Kakao", "Melk", "Smør"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva drikker man gjerne til frokost (fra ku)?", options: ["Juice", "Vann", "Brus", "Melk"], correctAnswerIndex: 3 },
    { category: "Mat og drikke", questionText: "Hvilken grønnsak gir deg angivelig godt syn?", options: ["Potet", "Gulrot", "Brokkoli", "Løk"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'bacon' laget av?", options: ["Ku", "Kylling", "Gris", "Sau"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilket land er kjent for taco?", options: ["Spania", "Mexico", "Italia", "USA"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva heter det man spiser med pinner i Kina?", options: ["Suppe", "Brød", "Ris/Nudler", "Pizza"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er 'Pepsi Max'?", options: ["Juice", "Vann", "Brus", "Melk"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er hovedingrediensen i ketchup?", options: ["Paprika", "Tomat", "Chili", "Løk"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hvilken fisk brukes i 'Fish and Chips'?", options: ["Laks", "Torsk", "Sild", "Makrell"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva kalles tørkede druer?", options: ["Svisker", "Rosiner", "Aprikos", "Dadler"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'Earl Grey'?", options: ["Kaffe", "Te", "Kakao", "Saft"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hvilken frukt er gul og bøyd?", options: ["Pære", "Eple", "Banan", "Mango"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er 'mozzarella'?", options: ["Pølse", "Skinke", "Ost", "Brød"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hva er 'basilikum'?", options: ["Kjøtt", "Krydderurt", "Frukt", "Grønnsak"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'espresso'?", options: ["Sterk kaffe", "Varm sjokolade", "Te med melk", "Fruktjuice"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken matrett er Garfield (katten) glad i?", options: ["Pizza", "Lasagne", "Taco", "Sushi"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'tortilla'?", options: ["En suppe", "Et brød/lefse", "En saus", "En dessert"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'pinnekjøtt' laget av?", options: ["Gris", "Storfe", "Lam/Sau", "Kylling"], correctAnswerIndex: 2 },
    { category: "Mat og drikke", questionText: "Hvilken frukt har piggete skall og gult kjøtt?", options: ["Melon", "Ananas", "Mango", "Papaya"], correctAnswerIndex: 1 },
    { category: "Mat og drikke", questionText: "Hva er 'wasabi'?", options: ["Sterk grønn pasta", "Søt saus", "Salt kjeks", "Surt godteri"], correctAnswerIndex: 0 },
    { category: "Mat og drikke", questionText: "Hvilken nøtt er grønn inni?", options: ["Valnøtt", "Pistasj", "Peanøtt", "Mandler"], correctAnswerIndex: 1 }
];
