export const PART_1 = [
    // --- SPORT (50) ---
    { category: "Sport", questionText: "Hvilket land vant fotball-VM for menn i 2018?", options: ["Brasil", "Tyskland", "Frankrike", "Spania"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvor mange spillere er det på et håndballag (på banen)?", options: ["5", "6", "7", "8"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva heter den raskeste mannen i verden (100m rekord)?", options: ["Tyson Gay", "Usain Bolt", "Asafa Powell", "Carl Lewis"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken idrett bruker man en 'puck'?", options: ["Innebandy", "Ishockey", "Landhockey", "Curling"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken farge har ledertrøya i Tour de France?", options: ["Gul", "Rød", "Grønn", "Hvit"], correctAnswerIndex: 0 },
    { category: "Sport", questionText: "Hvor mange ruter er det på et sjakkbrett?", options: ["56", "64", "72", "81"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken norsk sjakkspiller har vært verdensmester?", options: ["Magnus Carlsen", "Simen Agdestein", "Jon Ludvig Hammer", "Aryan Tari"], correctAnswerIndex: 0 },
    { category: "Sport", questionText: "Hva heter hjemmebanen til Manchester United?", options: ["Anfield", "Etihad Stadium", "Old Trafford", "Stamford Bridge"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvilken idrett er Erling Braut Haaland kjent for?", options: ["Langrenn", "Fotball", "Håndball", "Friidrett"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvor arrangeres OL vanligvis hvert ... år?", options: ["2. år", "3. år", "4. år", "5. år"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvem er kjent som 'The King of Clay' i tennis?", options: ["Roger Federer", "Novak Djokovic", "Rafael Nadal", "Andy Murray"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvilket lag vant Premier League sesongen 2022/2023?", options: ["Arsenal", "Liverpool", "Manchester City", "Manchester United"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva heter den norske kvinnelige langrennsdronningen med flest VM-gull?", options: ["Therese Johaug", "Marit Bjørgen", "Heidi Weng", "Ingvild Flugstad Østberg"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken idrett konkurrerer Viktor Hovland?", options: ["Tennis", "Golf", "Sjakk", "Friidrett"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvor mange poeng får man for touchdown i amerikansk fotball?", options: ["3", "5", "6", "7"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva kalles det når en bowler slår ned alle kjeglene på første kast?", options: ["Spare", "Strike", "Split", "Turkey"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken by arrangerte sommer-OL i 2012?", options: ["Beijing", "London", "Rio de Janeiro", "Tokyo"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken idrett bruker man begrepet 'offside'?", options: ["Tennis", "Fotball", "Golf", "Volleyball"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvem har vunnet flest Grand Slam-titler i tennis på herresiden (per 2023)?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva heter den kjente basketballspilleren som spilte for Chicago Bulls med nummer 23?", options: ["LeBron James", "Kobe Bryant", "Michael Jordan", "Shaquille O'Neal"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvor lang er en maraton?", options: ["30 km", "40 km", "42,195 km", "50 km"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvilket land kommer fotballspilleren Lionel Messi fra?", options: ["Spania", "Brasil", "Argentina", "Portugal"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva heter den norske hekkeløperen som satte verdensrekord i OL i Tokyo?", options: ["Jakob Ingebrigtsen", "Karsten Warholm", "Narve Gilje Nordås", "Filip Ingebrigtsen"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken idrett er 'birkebeinerrennet'?", options: ["Sykling", "Løping", "Langrenn", "Svømming"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva kalles målvakten i ishockey?", options: ["Keeper", "Goalie", "Stopper", "Vakt"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken farge er det på beltet til en nybegynner i karate?", options: ["Svart", "Hvitt", "Gult", "Blått"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hva heter det nasjonale fotballstadionet i Norge?", options: ["Lerkendal", "Brann Stadion", "Ullevaal Stadion", "Intility Arena"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvor mange hull er det på en standard golfbane?", options: ["9", "12", "18", "24"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "I hvilken sport benyttes en 'shuttlecock' (fjærball)?", options: ["Tennis", "Badminton", "Squash", "Bordtennis"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilket år ble OL på Lillehammer arrangert?", options: ["1992", "1994", "1996", "1998"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvem vant kvinnenes håndball-VM i 2021?", options: ["Frankrike", "Russland", "Norge", "Danmark"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvilken bilfabrikant kjører Lewis Hamilton for i Formel 1 (2023)?", options: ["Red Bull", "Ferrari", "Mercedes", "McLaren"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva heter den kjente sykkelrittet i Italia?", options: ["Tour de France", "Vuelta a España", "Giro d'Italia", "Arctic Race"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvor mange omganger er det i en vanlig fotballkamp?", options: ["1", "2", "3", "4"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken idrett hopper man 'Fosbury Flop'?", options: ["Lengdehopp", "Høydehopp", "Stavsprang", "Tresteg"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilket land er kjent for 'All Blacks' i rugby?", options: ["Australia", "Sør-Afrika", "New Zealand", "England"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hva er maks score i bowling?", options: ["200", "250", "300", "350"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvilken norsk alpinist har kallenavnet 'The Attacking Viking'?", options: ["Kjetil André Aamodt", "Aksel Lund Svindal", "Henrik Kristoffersen", "Aleksander Aamodt Kilde"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvor mange ringer er det i det olympiske flagget?", options: ["4", "5", "6", "7"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken idrett driver Casper Ruud med?", options: ["Golf", "Tennis", "Ski", "Fotball"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hva kalles det når en tennisspiller server et 'ess'?", options: ["Ballen treffer nettet", "Motstanderen rører ikke ballen", "Ballen går ut", "Dobbeltslag"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken amerikansk by ligger lagene 'Knicks' og 'Rangers'?", options: ["Los Angeles", "Chicago", "New York", "Boston"], correctAnswerIndex: 2 },
    { category: "Sport", questionText: "Hvem er manager for Manchester City (2023)?", options: ["Jurgen Klopp", "Pep Guardiola", "Erik ten Hag", "Mikel Arteta"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hva heter verdens største sykkelritt?", options: ["Giro Italia", "Tour de France", "Spania Rundt", "VM i landevei"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilket land vant EM i fotball 2020 (spilt i 2021)?", options: ["England", "Italia", "Spania", "Danmark"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "I hvilken sport bruker man begrepet 'hole in one'?", options: ["Minigolf", "Biljard", "Fotballgolf", "Golf"], correctAnswerIndex: 3 },
    { category: "Sport", questionText: "Hvem har verdensrekorden på 400 meter hekk?", options: ["Edwin Moses", "Karsten Warholm", "Rai Benjamin", "Kevin Young"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hva heter det norske kvinnelandslagets trener i håndball (2023)?", options: ["Marit Breivik", "Thorir Hergeirsson", "Mia Hundvin", "Ole Gustav Gjekstad"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilket lag spiller på Anfield?", options: ["Everton", "Liverpool", "Chelsea", "Arsenal"], correctAnswerIndex: 1 },
    { category: "Sport", questionText: "Hvilken nasjon har vunnet flest vinter-OL medaljer totalt?", options: ["USA", "Tyskland", "Norge", "Russland"], correctAnswerIndex: 2 },

    // --- MUSIKK (50) ---
    { category: "Musikk", questionText: "Hvem er kjent som 'Kongen av Pop'?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilket instrument spiller Ole Bull?", options: ["Piano", "Gitar", "Fiolin", "Fløyte"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilken gruppe sang 'Dancing Queen'?", options: ["Beatles", "ABBA", "Queen", "Spice Girls"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hva heter vokalisten i U2?", options: ["Sting", "Bono", "The Edge", "Slash"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvor mange strenger har en standard gitar?", options: ["4", "5", "6", "7"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvem vant Eurovision Song Contest for Norge i 2009?", options: ["Bobbysocks", "Secret Garden", "Alexander Rybak", "Keiino"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilken artist ga ut albumet 'Thriller'?", options: ["Prince", "Madonna", "Michael Jackson", "Whitney Houston"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilket band har hits som 'Yellow' og 'Viva La Vida'?", options: ["Radiohead", "Muse", "Coldplay", "Oasis"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hva er artistnavnet til Marshall Mathers?", options: ["50 Cent", "Jay-Z", "Eminem", "Snoop Dogg"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilken norsk artist står bak låten 'Alone'?", options: ["Kygo", "Alan Walker", "Matoma", "Aurora"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilket år døde Elvis Presley?", options: ["1975", "1977", "1980", "1982"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'Hello'?", options: ["Beyoncé", "Adele", "Rihanna", "Taylor Swift"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilket norsk band sanger om 'Forelska i lærer'n'?", options: ["The Kids", "TNT", "DumDum Boys", "Jokke & Valentinerne"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvem er kjent som 'The Boss'?", options: ["Bob Dylan", "Bruce Springsteen", "Tom Petty", "Elton John"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilket instrument spiller Lang Lang?", options: ["Fiolin", "Cello", "Piano", "Trompet"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hva heter vokalisten i The Rolling Stones?", options: ["Keith Richards", "Mick Jagger", "Paul McCartney", "Robert Plant"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilken sjanger er Bob Marley kjent for?", options: ["Rock", "Reggae", "Jazz", "Blues"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'Shape of You'?", options: ["Justin Bieber", "Harry Styles", "Ed Sheeran", "Shawn Mendes"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilket instrument har svarte og hvite tangenter?", options: ["Gitar", "Trommer", "Piano", "Fløyte"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvem vant Idol i Norge første sesong (2003)?", options: ["Tone Damli", "Kurt Nilsen", "Alejandro Fuentes", "Jorun Stiansen"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilken by kommer The Beatles fra?", options: ["London", "Manchester", "Liverpool", "Birmingham"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hva heter den norske nasjonalsangen?", options: ["Norge i rødt, hvitt og blått", "Ja, vi elsker dette landet", "Mellom bakkar og berg", "Gud signe vårt dyre fedreland"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'I Will Always Love You' (kjent cover)?", options: ["Mariah Carey", "Céline Dion", "Whitney Houston", "Aretha Franklin"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilken komponist skrev 'Skjebnesymfonien'?", options: ["Mozart", "Beethoven", "Bach", "Grieg"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem er datteren til Billy Ray Cyrus?", options: ["Miley Cyrus", "Katy Perry", "Selena Gomez", "Demi Lovato"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilken norsk gruppe hadde suksess med 'Take on Me'?", options: ["Röyksopp", "A-ha", "Madcon", "Ylvis"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem kalles 'Queen of Pop'?", options: ["Madonna", "Britney Spears", "Lady Gaga", "Cher"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilket instrument er hovedinstrumentet til Louis Armstrong?", options: ["Saksofon", "Trompet", "Klarinett", "Trombone"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'Bad Guy'?", options: ["Ariana Grande", "Billie Eilish", "Dua Lipa", "Halsey"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvilken norsk duo består av Nico & Vinz?", options: ["Nicolay og Vincent", "Nils og Vidar", "Nicolai og Vincent", "Kahouly og Vincent"], correctAnswerIndex: 3 },
    { category: "Musikk", questionText: "Hva heter trommeslageren i The Beatles?", options: ["John Lennon", "George Harrison", "Paul McCartney", "Ringo Starr"], correctAnswerIndex: 3 },
    { category: "Musikk", questionText: "I hvilket tiår var disco mest populært?", options: ["60-tallet", "70-tallet", "80-tallet", "90-tallet"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem har låten 'Purple Rain'?", options: ["Prince", "David Bowie", "Jimi Hendrix", "Stevie Wonder"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvem er vokalist i bandet Coldplay?", options: ["Chris Martin", "Dave Grohl", "Thom Yorke", "Liam Gallagher"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilket land kommer DJ-en Avicii fra?", options: ["Norge", "Sverige", "Danmark", "Finland"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hva heter operaen som ligger i Bjørvika i Oslo?", options: ["Grieghallen", "Den Norske Opera & Ballett", "Nationaltheatret", "Konserthuset"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'Bohemian Rhapsody'?", options: ["Queen", "Led Zeppelin", "Pink Floyd", "The Rolling Stones"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilken artist er kjent for 'Rocket Man'?", options: ["David Bowie", "Elton John", "Billy Joel", "Rod Stewart"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem var gift med Beyoncé?", options: ["Kanye West", "Drake", "Jay-Z", "Usher"], correctAnswerIndex: 2 },
    { category: "Musikk", questionText: "Hvilket instrument spiller Edvard Grieg?", options: ["Fiolin", "Piano", "Gitar", "Cello"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hva heter den årlige musikkfestivalen i Indre Østfold (som var)?", options: ["Øyafestivalen", "Momarkedet", "Slottsfjell", "Palmesus"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem synger 'Wrecking Ball'?", options: ["Miley Cyrus", "Rihanna", "Sia", "Pink"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilken norsk artist vant MGP jr. med 'To dråper vann'?", options: ["Marcus & Martinus", "Sval", "Malin Reitan", "Mathea-Mari"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvem spilte gitar i Guns N' Roses?", options: ["Axl Rose", "Slash", "Duff McKagan", "Izzy Stradlin"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hva heter debutalbumet til Kygo?", options: ["Cloud Nine", "Kids in Love", "Golden Hour", "Stargazing"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvem synger duett med Bradley Cooper i filmen 'A Star Is Born'?", options: ["Lady Gaga", "Miley Cyrus", "Adele", "Beyoncé"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilket band har en tunge som logo?", options: ["Kiss", "The Rolling Stones", "AC/DC", "Nirvana"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hvem er kjent for sangen '9 til 5'?", options: ["Dolly Parton", "Loretta Lynn", "Shania Twain", "Reba McEntire"], correctAnswerIndex: 0 },
    { category: "Musikk", questionText: "Hvilken norsk svartmetall-gruppe er verdenskjent?", options: ["Turbonegro", "Dimmu Borgir", "Kaizers Orchestra", "Highasakite"], correctAnswerIndex: 1 },
    { category: "Musikk", questionText: "Hva heter artisten som kaller seg 'The Weeknd'?", options: ["Abel Tesfaye", "Aubrey Graham", "Shawn Carter", "Robyn Fenty"], correctAnswerIndex: 0 },


    // --- FILM OG TV (50) ---
    { category: "Film og TV", questionText: "Hvem spilte rollen som Jack Dawson i 'Titanic'?", options: ["Brad Pitt", "Tom Cruise", "Leonardo DiCaprio", "Johnny Depp"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva heter løven i 'Løvenes Konge'?", options: ["Mufasa", "Simba", "Scar", "Timon"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken filmserie handler om en ring?", options: ["Harry Potter", "Ringenes Herre", "Star Wars", "Hunger Games"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter snømannen i 'Frost'?", options: ["Sven", "Kristoff", "Olaf", "Hans"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvem er skaperen av 'Star Wars'?", options: ["Steven Spielberg", "George Lucas", "James Cameron", "Peter Jackson"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken farge er det på pillen Neo tar i 'The Matrix'?", options: ["Blå", "Rød", "Grønn", "Gul"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter den kjente vennegjengen i TV-serien 'Friends' (en av dem)?", options: ["Ted", "Barney", "Ross", "Sheldon"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvilken skuespiller spiller 'Iron Man'?", options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva er navnet på trollmannsskolen i Harry Potter?", options: ["Durmstrang", "Beauxbatons", "Hogwarts", "Ilvermorny"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "I hvilken by foregår serien 'Stranger Things' (hovedsakelig)?", options: ["Hawkins", "Riverdale", "Smallville", "Twin Peaks"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken film vant Oscar for beste film i 2020 (første ikke-engelske)?", options: ["Roma", "Parasite", "Amour", "Crouching Tiger"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter hovedkarakteren i 'Pirates of the Caribbean'?", options: ["Will Turner", "Davy Jones", "Jack Sparrow", "Barbossa"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvilken planet kommer Supermann fra?", options: ["Mars", "Krypton", "Jupiter", "Saturn"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvem spiller hovedrollen i 'Forrest Gump'?", options: ["Tom Hanks", "Robin Williams", "Harrison Ford", "Mel Gibson"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hva heter leketøys-cowboyen i 'Toy Story'?", options: ["Buzz", "Woody", "Rex", "Slinky"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "I hvilken serie finner du karakteren 'Walter White'?", options: ["The Sopranos", "The Wire", "Breaking Bad", "Mad Men"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvem spiller rollen som 'The Joker' i 'The Dark Knight'?", options: ["Jack Nicholson", "Jared Leto", "Heath Ledger", "Joaquin Phoenix"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva heter dragen i 'Hobbiten'?", options: ["Smaug", "Drogon", "Norbert", "Toothless"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hva er navnet på den fiktive byen i 'Simpsons'?", options: ["South Park", "Quahog", "Springfield", "Gotham"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvilken film er kjent for sitatet 'I'll be back'?", options: ["Rocky", "Die Hard", "The Terminator", "Rambo"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvem er stemmen til muldyret i 'Shrek' på engelsk?", options: ["Mike Myers", "Eddie Murphy", "Cameron Diaz", "Antonio Banderas"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken film handler om dinosaurer som vekkes til live?", options: ["King Kong", "Jurassic Park", "Godzilla", "Ice Age"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter søsteren til Elsa i 'Frost'?", options: ["Anna", "Rapunzel", "Moana", "Tiana"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken norsk film ble nominert til Oscar i 2022?", options: ["Kongens nei", "Kon-Tiki", "Verdens verste menneske", "Håp"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva heter den grønne figuren fra Star Wars som snakker baklengs?", options: ["Chewbacca", "Yoda", "Jabba", "Ewok"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvem spilte 'James Bond' før Daniel Craig?", options: ["Roger Moore", "Sean Connery", "Pierce Brosnan", "Timothy Dalton"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "I hvilken film møter vi 'Dory'?", options: ["Oppdrag Nemo", "Innsiden Ut", "Biler", "De utrolige"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hva heter hovedstaden i 'The Hunger Games'?", options: ["District 12", "Panem", "The Capitol", "Mockingjay"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvilken skuespiller spiller 'Black Widow'?", options: ["Scarlett Johansson", "Jennifer Lawrence", "Gal Gadot", "Angelina Jolie"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hva heter bjørnen i 'Jungelboken'?", options: ["Bagheera", "Kaa", "Baloo", "Shere Khan"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvem har regissert 'Pulp Fiction'?", options: ["Martin Scorsese", "Quentin Tarantino", "Christopher Nolan", "Francis Ford Coppola"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter den norske serien om ungdommer på Hartvig Nissen skole?", options: ["Rådebank", "Skam", "Exit", "Unge lovende"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken filmserie har karakteren 'Gollum'?", options: ["Harry Potter", "Ringenes Herre", "Narnia", "Game of Thrones"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva er navnet på Batmans butler?", options: ["Alfred", "Robin", "Gordon", "Lucius"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken frukt bor 'Svampebob' i?", options: ["Eple", "Banan", "Ananas", "Pære"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvem spiller 'Wonder Woman' (2017)?", options: ["Gal Gadot", "Brie Larson", "Margot Robbie", "Jessica Alba"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hva heter hunden til 'Tintin'?", options: ["Milou", "Pluto", "Snoopy", "Lassie"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken farge har lyssverdet til Darth Vader?", options: ["Blått", "Grønt", "Rødt", "Lilla"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "I hvilken film sier de 'May the Force be with you'?", options: ["Star Trek", "Star Wars", "E.T.", "Avatar"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter hovedpersonen i 'The Office' (US)?", options: ["Jim Halpert", "Dwight Schrute", "Michael Scott", "Pam Beesly"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hvilket hus hører Harry Potter til?", options: ["Slytherin", "Hufflepuff", "Ravenclaw", "Gryffindor"], correctAnswerIndex: 3 },
    { category: "Film og TV", questionText: "Hvem er fienden i 'Peter Pan'?", options: ["Kaptein Krok", "Smee", "Rufus", "Jafar"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken skuespillerinne spilte 'Hermine Grang'?", options: ["Emma Stone", "Emma Watson", "Emma Roberts", "Emma Thompson"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hva heter filmen om Facebook?", options: ["The Internet", "The Social Network", "Connected", "Friends"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken by blir ødelagt i 'Godzilla'?", options: ["New York", "London", "Tokyo", "Paris"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva heter hovedpersonen i 'Hjemme Alene'?", options: ["Kevin", "Harry", "Marv", "Buzz"], correctAnswerIndex: 0 },
    { category: "Film og TV", questionText: "Hvilken TV-serie handler om drakene Targaryen?", options: ["The Witcher", "House of the Dragon", "Rings of Power", "Vikings"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvem spiller 'Thor' i Mavel-filmene?", options: ["Chris Pratt", "Chris Evans", "Chris Hemsworth", "Tom Hiddleston"], correctAnswerIndex: 2 },
    { category: "Film og TV", questionText: "Hva heter krabben i 'Den lille havfruen'?", options: ["Flounder", "Sebastian", "Scuttle", "Triton"], correctAnswerIndex: 1 },
    { category: "Film og TV", questionText: "Hvilken film vant Oscar for beste animasjonsfilm i 2001 (første året prisen ble delt ut)?", options: ["Toy Story", "Shrek", "Istid", "Monsterbedriften"], correctAnswerIndex: 1 },


    // --- HISTORIE (50) ---
    { category: "Historie", questionText: "Når startet andre verdenskrig?", options: ["1914", "1918", "1939", "1945"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem oppdaget Amerika i 1492?", options: ["Leiv Eiriksson", "Kristoffer Columbus", "Vasco da Gama", "Ferdinand Magellan"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Når ble den norske grunnloven underskrevet?", options: ["1814", "1905", "1945", "1030"], correctAnswerIndex: 0 },
    { category: "Historie", questionText: "Hvilket land var Napoleon keiser i?", options: ["Italia", "Spania", "Frankrike", "Tyskland"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem var den første mannen på månen?", options: ["Yuri Gagarin", "Buzz Aldrin", "Neil Armstrong", "Michael Collins"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hva het skipet til Roald Amundsen?", options: ["Fram", "Kon-Tiki", "Gjøa", "Norge"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilken mur falt i 1989?", options: ["Den kinesiske mur", "Berlinmuren", "Hadrians mur", "Klagemuren"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvem malte 'Mona Lisa'?", options: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Michelangelo"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Når skjedde terrorangrepet i USA kjent som 9/11?", options: ["1999", "2000", "2001", "2002"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilket rike hersket Julius Cæsar over?", options: ["Det osmanske riket", "Romerriket", "Det britiske imperiet", "Mongolriket"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Når ble unionen med Sverige oppløst?", options: ["1814", "1905", "1914", "1940"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilken vikingkonge falt på Stiklestad?", options: ["Harald Hårfagre", "Olav Tryggvason", "Olav den Hellige", "Eirik Blodøks"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem var Storbritannias statsminister under andre verdenskrig?", options: ["Neville Chamberlain", "Winston Churchill", "Margaret Thatcher", "Tony Blair"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilket år sluttet første verdenskrig?", options: ["1916", "1917", "1918", "1919"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hva het skipet som sank i 1912?", options: ["Britannic", "Olympic", "Titanic", "Lusitania"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilken by ble rammet av en atombombe i 1945?", options: ["Tokyo", "Hiroshima", "Kyoto", "Osaka"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvem var president i USA under borgerkrigen?", options: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "Theodore Roosevelt"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilket land bygde de store pyramidene?", options: ["Hellas", "Roma", "Egypt", "Persia"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem skrev dagbok mens hun gjemte seg for nazistene?", options: ["Anne Frank", "Rosa Parks", "Marie Curie", "Florence Nightingale"], correctAnswerIndex: 0 },
    { category: "Historie", questionText: "Hva kaltes perioden i Norge fra 800-1050?", options: ["Steinalderen", "Bronsealderen", "Vikingtiden", "Middelalderen"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilken norsk oppdager krysset Stillehavet på flåten Kon-Tiki?", options: ["Fridtjof Nansen", "Roald Amundsen", "Thor Heyerdahl", "Helge Ingstad"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem var den første kvinnelige statsministeren i Norge?", options: ["Erna Solberg", "Gro Harlem Brundtland", "Siv Jensen", "Kristin Halvorsen"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilket år falt Berlinmuren?", options: ["1987", "1988", "1989", "1990"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hva het den russiske tsarfamilien som ble henrettet i 1918?", options: ["Habsburg", "Romanov", "Bourbon", "Windsor"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvem ledet kampen mot apartheid i Sør-Afrika?", options: ["Martin Luther King", "Mahatma Gandhi", "Nelson Mandela", "Desmond Tutu"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Når fikk kvinner stemmerett i Norge?", options: ["1905", "1910", "1913", "1920"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem sies å ha oppfunnet lyspæren?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Benjamin Franklin"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilken sivilisasjon bygde Machu Picchu?", options: ["Aztekerne", "Mayaene", "Inkaene", "Olmec"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem startet reformasjonen i 1517?", options: ["Jean Calvin", "Martin Luther", "Henrik VIII", "Pave Leo X"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilken krig varte fra 1950 til 1953?", options: ["Vietnamkrigen", "Koreakrigen", "Golfkrigen", "Falklandskrigen"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvem var dronning av Storbritannia i over 60 år (før Elizabeth II)?", options: ["Victoria", "Elizabeth I", "Mary", "Anne"], correctAnswerIndex: 0 },
    { category: "Historie", questionText: "Hvilket år landet mennesket på månen?", options: ["1965", "1967", "1969", "1971"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem var den første presidenten i USA?", options: ["Abraham Lincoln", "Thomas Jefferson", "George Washington", "John Adams"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilken pest rammet Europa på 1300-tallet?", options: ["Spanskesyken", "Svartedauden", "Kopper", "Kolera"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hva het den kalde krigen mellom USA og ...?", options: ["Kina", "Tyskland", "Sovjetunionen", "Japan"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilken norsk konge sa 'Alt for Norge'?", options: ["Haakon VII", "Olav V", "Harald V", "Alle tre"], correctAnswerIndex: 3 },
    { category: "Historie", questionText: "Hvem ble skutt i Dallas i 1963?", options: ["Abraham Lincoln", "Robert Kennedy", "John F. Kennedy", "Martin Luther King"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilket land angrep Pearl Harbor?", options: ["Tyskland", "Kina", "Japan", "Italia"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem var diktator i Tyskland under 2. verdenskrig?", options: ["Benito Mussolini", "Adolf Hitler", "Joseph Stalin", "Franco"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hva var navnet på skipet til kaptein Cook?", options: ["Endeavour", "Beagle", "Santa Maria", "Victoria"], correctAnswerIndex: 0 },
    { category: "Historie", questionText: "Når ble Norge okkupert av Tyskland?", options: ["1939", "1940", "1941", "1942"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilken mur delte Berlin?", options: ["Jernteppet", "Berlinmuren", "Antifascistmuren", "Vestmuren"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hva heter slottet der den franske kongefamilien bodde?", options: ["Louvre", "Versailles", "Bastillen", "Notre Dame"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvem var leder for Sovjetunionen under 2. verdenskrig?", options: ["Lenin", "Stalin", "Gorbatsjov", "Putin"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hvilken kjent handelsrute gikk mellom Europa og Kina?", options: ["Saltveien", "Silkeveien", "Krydderveien", "Gullruten"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hva het den første hunden i verdensrommet?", options: ["Belka", "Strelka", "Laika", "Rex"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvilket år ble Facebook grunnlagt?", options: ["2000", "2002", "2004", "2006"], correctAnswerIndex: 2 },
    { category: "Historie", questionText: "Hvem malte taket i det sixtinske kapell?", options: ["Rafael", "Donatello", "Leonardo", "Michelangelo"], correctAnswerIndex: 3 },
    { category: "Historie", questionText: "Hvilken by ble grunnlagt av Romulus og Remus?", options: ["Athen", "Roma", "Sparta", "Troja"], correctAnswerIndex: 1 },
    { category: "Historie", questionText: "Hva het skipet som fraktet pilegrimene til Amerika i 1620?", options: ["Mayflower", "Santa Maria", "Nina", "Pinta"], correctAnswerIndex: 0 }
];
